# Generated by Django 5.2.7 on 2025-10-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='blockchain_tx',
            new_name='transaction_hash',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='predicted_emission',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
