# Generated by Django 4.2 on 2025-12-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_activity_options_activity_token_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='listing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='marketplace_status',
            field=models.CharField(choices=[('not_listed', 'Not Listed'), ('listed', 'Listed for Sale'), ('sold', 'Sold')], default='not_listed', max_length=20),
        ),
    ]
